server:
  port: 18081
#FastDFS配置
fastdfs:
  url: http://192.168.211.137:28181/
  fdfsPrefix: png,jpg #上传前缀配置，默认上传到FastDFS
#aliyun
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKey: a7i6rVEjbtaJdYX2
    accessKeySecret: MeSZPybPHfJtsYCRlEaUbfRtdH8gl4
    bucketName: sklll
    key: video/
    ossPrefix: avi,mp4  #上传文件前缀配置
    backurl: https://sklll.oss-cn-beijing.aliyuncs.com/video/ #访问地址配置

spring:
  application:
    name: seckill-goods
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB #上传文件大小配置

#支付通道列表
pay:
  paymap: {"1":"weixinPay","2":"aliPay"}
